name: Update Branches

on:
  workflow_dispatch:

jobs:
  update-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Set GitHub CLI Authentication
        run: echo "GH_TOKEN=${{ secrets.PAT }}" >> $GITHUB_ENV

      - name: Run branch update script
        run: |
          chmod +x scripts/create-protect-branch.sh
          scripts/create-protect-branch.sh testorg8041 "${{ secrets.PAT }}"
        env:
          PAT: ${{ secrets.PAT }}
